# General customisation
# Force to use all OpenCMISS dependencies - long compilation, but will work
SET(FORCE_OCM_ALLDEPS NO)
# Compile tests?
ENABLE_TESTING()

# Debug customisation
SET(DEBUG_ALL NO)
# Single packages
SET(DEBUG_BLAS NO)
SET(DEBUG_LAPACK NO)
SET(DEBUG_PLAPACK NO)
SET(DEBUG_SCALAPACK NO)
SET(DEBUG_PARMETIS NO)
SET(DEBUG_CHOLMOD NO)

# ==============================
# customisation of dependencies
# ==============================
# BLAS 
#SET(BLAS_LIBRARIES )
#SET(BLAS_INCLUDES )
SET(OCM_FORCE_BLAS NO)

# LAPACK
#SET(LAPACK_LIBRARIES )
#SET(LAPACK_INCLUDES )
SET(OCM_FORCE_LAPACK NO)

# PLAPACK
#SET(PLAPACK_LIBRARIES )
#SET(PLAPACK_INCLUDES )
SET(OCM_FORCE_PLAPACK NO)

# SCALAPACK
#SET(SCALAPACK_LIBRARIES )
#SET(SCALAPACK_INCLUDES )
SET(OCM_FORCE_SCALAPACK NO)

# PARMETIS
#SET(PARMETIS_LIBRARIES )
#SET(PARMETIS_INCLUDES )
SET(OCM_USE_PARMETIS YES)
SET(OCM_FORCE_PARMETIS NO)


# MUMPS
#SET(MUMPS_LIBRARIES )
#SET(MUMPS_INCLUDES )
SET(OCM_FORCE_MUMPS NO)

# CHOLMOD
#SET(CHOLMOD_LIBRARIES )
#SET(CHOLMOD_INCLUDES )
SET(OCM_FORCE_CHOLMOD NO)